# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-null-ansible
  description: Terraform Module to run ansible playbooks
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, ansible, playbook, ansible-playbook, hcl2



